# Generated by Django 5.2.16 on 2026-07-12 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('foundation', 'Foundation'), ('core', 'Core'), ('advanced', 'Advanced')], default='core', max_length=20)),
                ('patient_story', models.TextField(help_text='Full background story for the LLM system prompt')),
                ('patient_role', models.CharField(help_text="Personality descriptor, e.g. 'anxious but cooperative'", max_length=200)),
                ('expected_diagnosis', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['specialty', 'difficulty', 'title'],
            },
        ),
    ]
