# Generated by Django 5.2.16 on 2026-07-12 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('complete', 'Complete')], default='active', max_length=20)),
                ('messages', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='apps_cases.patientcase')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
